name: Deploy to Glitch
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Deploy To Glitch
        uses: kanadgupta/glitch-sync@master
        with:
          project-id: ${{ secrets.PROJECT_ID }}
          auth-token: ${{ secrets.AUTH_TOKEN }}
      - run: "curl -H \"Content-Type: application/json\" -X POST -d '{\"content\": \"Deployed `github:Jinno19/portal-scraping` to `glitch:tut-scraping`\"}' ${{secrets.DISCORD_WEBHOOK_URL}}"
